version: '3'
services:
  vue-image-uploader:
    image: vue-image-uploader:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-image-uploader
    volumes:
      - ./:/app/
    ports:
      - 8080:8080